CREATE DATABASE IF NOT EXISTS adesicristi;
USE adesicristi;

CREATE TABLE IF NOT EXISTS admin_users (
  id INT AUTO_INCREMENT PRIMARY KEY,
  username VARCHAR(100) NOT NULL UNIQUE,
  password VARCHAR(255) NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS rsvp_responses (
  id INT AUTO_INCREMENT PRIMARY KEY,
  person_count TINYINT NOT NULL,
  name VARCHAR(200) NOT NULL,
  partner_name VARCHAR(200) NULL,
  message TEXT NULL,
  attending BOOLEAN NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
