USE adesicristi;

CREATE TABLE IF NOT EXISTS guests (
  id INT AUTO_INCREMENT PRIMARY KEY,
  nume VARCHAR(200) NOT NULL,
  prenume VARCHAR(200) NOT NULL,
  plus_one BOOLEAN NOT NULL DEFAULT FALSE,
  intro TEXT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
