CREATE TABLE IF NOT EXISTS bar_items (
  id INT AUTO_INCREMENT PRIMARY KEY,
  titlu VARCHAR(255) NOT NULL,
  descriere TEXT,
  categorie ENUM('alcoolic', 'non_alcoolic') NOT NULL DEFAULT 'alcoolic',
  ordine INT NOT NULL DEFAULT 0,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
